name: SSH with sshx (24/7)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"   # auto restart every 6 hours

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
    - name: Change Hostname
      run: sudo hostnamectl set-hostname axolotlvm

    - name: Setup OpenSSH
      run: |
        sudo apt update
        sudo apt install -y openssh-server
        sudo systemctl enable ssh
        sudo systemctl start ssh
        echo "root:root" | sudo chpasswd

    - name: Start sshx.io tunnel (auto-restart)
      run: |
        while true; do
          echo "Starting sshx.io tunnel..."
          curl -sSf https://sshx.io/get | sh || echo "sshx failed, retrying..."
          echo "Tunnel crashed or closed. Restarting in 5s..."
          sleep 5
        done

    - name: Keep Alive Runner
      run: |
        echo "Runner alive, keeping sshx active."
        while true; do sleep 60; done
